// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_base_counts
IntegerMatrix cpp_base_counts(CharacterVector seqs);
RcppExport SEXP _TmCalculator_cpp_base_counts(SEXP seqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seqs(seqsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_base_counts(seqs));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tm_nn_dhds
NumericMatrix cpp_tm_nn_dhds(CharacterVector seqs, CharacterVector cseqs, int shift, List nn, List tmm, List imm, List de, bool self_comp_eff, List end);
RcppExport SEXP _TmCalculator_cpp_tm_nn_dhds(SEXP seqsSEXP, SEXP cseqsSEXP, SEXP shiftSEXP, SEXP nnSEXP, SEXP tmmSEXP, SEXP immSEXP, SEXP deSEXP, SEXP self_comp_effSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cseqs(cseqsSEXP);
    Rcpp::traits::input_parameter< int >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< List >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< List >::type tmm(tmmSEXP);
    Rcpp::traits::input_parameter< List >::type imm(immSEXP);
    Rcpp::traits::input_parameter< List >::type de(deSEXP);
    Rcpp::traits::input_parameter< bool >::type self_comp_eff(self_comp_effSEXP);
    Rcpp::traits::input_parameter< List >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tm_nn_dhds(seqs, cseqs, shift, nn, tmm, imm, de, self_comp_eff, end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TmCalculator_cpp_base_counts", (DL_FUNC) &_TmCalculator_cpp_base_counts, 1},
    {"_TmCalculator_cpp_tm_nn_dhds", (DL_FUNC) &_TmCalculator_cpp_tm_nn_dhds, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_TmCalculator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
