# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_tm_nn_dhds <- function(seqs, cseqs, shift, nn, tmm, imm, de, self_comp_eff, end) {
    .Call(`_TmCalculator_cpp_tm_nn_dhds`, seqs, cseqs, shift, nn, tmm, imm, de, self_comp_eff, end)
}

